### ISSUE TITLE
Inconsistent metadata item for render modes.

### ISSUE THREAD

**Issue by jhenstra** [QuTech-Delft/qgym#64]
The key key used for the render modes metadata seems to be inconsistent with the [documentation](https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/#declaration-and-initialization) on custom environments. This is also the case for the other two environments.

It should be "render_modes" instead of "render.modes".

https://github.com/QuTech-Delft/qgym/blob/066f620c9a6113a4a8da45a746573a570553efe0/qgym/envs/routing/routing.py#L214C9-L214C65

**Comment by Willem-de-kok** [comment]
Thanks for the remark, I picked it up in #65.
